# what is numpy in python programming

NumPy is a fundamental library for numerical computing in Python. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these arrays efficiently.

Array Creation: You can create arrays using lists, tuples, or other array-like objects using numpy.array() or specialized functions like numpy.zeros(), numpy.ones(), numpy.arange(), numpy.linspace(), etc.

Array Attributes: Arrays have attributes like shape (dimensions), size (total number of elements), data type, etc.

Mathematical Operations:
NumPy enables element-wise operations, making it easy to perform arithmetic, logical, and statistical operations on arrays without using loops. These operations are often much faster than their pure Python counterparts

Array Indexing and Slicing:
NumPy supports advanced indexing techniques such as integer array indexing, Boolean indexing, and slicing, allowing for efficient and powerful manipulation of array data.

 Linear Algebra Operations:
NumPy provides various linear algebra functions to perform operations like matrix multiplication, matrix decomposition (e.g., Singular Value Decomposition, LU decomposition), matrix inversion, eigenvalues, etc

Why Use NumPy?

Performance: NumPy operations are implemented in C, making them much faster than pure Python operations on lists.

Memory Efficiency: NumPy arrays use less memory compared to Python lists.

Functionality: NumPy provides a wide range of mathematical functions and supports a variety of operations.


# Creating an array

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
# Creating arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.arange(6).reshape(2, 3)
print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)

Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[0 1 2]
 [3 4 5]]


# Mathematical operations

In [4]:

print("\nMathematical Operations:")
print("Element-wise addition:")
print(arr1 + arr2)





Mathematical Operations:
Element-wise addition:
[[ 1  3  5]
 [ 7  9 11]]


In [5]:
print("Element-wise multiplication:")
print(arr1 * arr2)

Element-wise multiplication:
[[ 0  2  6]
 [12 20 30]]


In [6]:
print("Dot product:")
print(np.dot(arr1, arr2))  # Transpose of arr2 for dot product

Dot product:


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

# aggregation opertaions

In [7]:
# Aggregation functions
arr1=([[2,3,2],[3,2,4]])
arr2=([[2,4,2],[5,6,8]])
print("some of array",np.sum(arr1))  # Sum of all elements in arr1

print("mean of array",np.mean(arr2, axis=1))  # Mean along axis 1 of arr2

print("maximum value in an array1",np.max(arr1))  # Maximum value in arr1

print("standard deviation of array2",np.std(arr2))  # Standard deviation of arr2


some of array 16
mean of array [2.66666667 6.33333333]
maximum value in an array1 4
standard deviation of array2 2.140872096444188


In [8]:
from scipy import stats
arr1=([[7,2,4],[9,2,4]])
mode=stats.mode(arr1)
print(mode)

ModeResult(mode=array([[7, 2, 4]]), count=array([[1, 2, 2]]))


# slicing operations in numpy

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing rows and columns
print(arr[:2, 1:])  # Slicing the first two rows and the last two columns



[[2 3]
 [5 6]]


# linear algebra operation 

In [10]:
import numpy as np

# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result_matrix_mul = np.dot(matrix1, matrix2)  # Matrix multiplication
print("Matrix Multiplication:")
print(result_matrix_mul)

# Matrix transpose
matrix_transpose = np.transpose(matrix1)  # Transpose of a matrix
print("\nMatrix Transpose:")
print(matrix_transpose)


Matrix Multiplication:
[[19 22]
 [43 50]]

Matrix Transpose:
[[1 3]
 [2 4]]


In [11]:
from scipy import stats
arr1=([[8,4,5],[7,4,6]])
mode_value=stats.mode(arr1)
print(mode_value)

ModeResult(mode=array([[7, 4, 5]]), count=array([[1, 2, 1]]))


In [12]:
from scipy import stats
import numpy as np

arr1 = np.array([[3, 4, 5], [7, 4, 6]])  # Convert to NumPy array
flattened_arr1 = arr1.flatten()  # Flatten the array

mode_value = stats.mode(flattened_arr1)
print(mode_value)


ModeResult(mode=array([4]), count=array([2]))


In [13]:
import numpy as np
arr1=([[3,4,5],[4,5,7]])
transpose=np.transpose(arr1)
print(transpose)

[[3 4]
 [4 5]
 [5 7]]


In [14]:
arr1=([4,5,6,46,7,5,43])
slice=arr1[2:7]
print(slice)

[6, 46, 7, 5, 43]


In [17]:
# Matrix operations
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

matrix_product = np.dot(matrix1, matrix2)  # Matrix multiplication
determinant = np.linalg.det(matrix1)  # Determinant of a matrix
inverse_matrix = np.linalg.inv(matrix2)  # Inverse of a matrix
print(" Matrix multiplication",matrix_product)
print("Determinant of a matrix",determinant)
print(" Inverse of a matrix",inverse_matrix)

 Matrix multiplication [[19 22]
 [43 50]]
Determinant of a matrix -2.0000000000000004
 Inverse of a matrix [[-4.   3. ]
 [ 3.5 -2.5]]
